"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BurgerMenu from "@/components/atoms/BurgerMenu";
import SideNav from "@/components/molecules/SideNav";
import { useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [displayedSideNav, setDisplayedSideNav] = useState(false);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-theme-dark text-theme-kaki relative`}
      >
        <BurgerMenu handleToggle={() => setDisplayedSideNav((p) => !p)} />
        <SideNav displayed={displayedSideNav} />
        {children}
      </body>
    </html>
  );
}
